name: Build and Publish Package & Push Git Tag

on:
  push:
    branches:
      - main

jobs:
  build-publish-pkg-push-tag:
    name: Build and Publish Package & Push Git Tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1

      - name: Show envs
        run: env

      - name: Build and Publish poetry
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ vars.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          poetry version patch
          poetry build
          poetry publish

      - name: Push bump commit and Create Tag
        run: |
          BUMP_VERSION=v$(poetry version --short)
          git add pyproject.toml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "bump up $BUMP_VERSION version from workflow"
          git push
          git tag $BUMP_VERSION
          git push origin $BUMP_VERSION
