name: Build and Publish Package & Push Git Tag

on:
  push:
    branches:
      - main

jobs:
  build-publish-pkg-push-tag:
    # if: ${{ !(contains(github.actor, '[bot]') && github.event_name == 'push') }}
    name: Build and Publish Package & Push Git Tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: env

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1

      - name: Build and Publish to PYPI
        env:
          POETRY_REQUESTS_TIMEOUT: 60
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          poetry version patch
          poetry build
          poetry publish --skip-existing

      - name: Push bump commit and Create Tag
        run: |
          BUMP_VERSION=v$(poetry version --short)
          git add pyproject.toml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "bump up $BUMP_VERSION version from workflow"
          git push
          git tag $BUMP_VERSION
          git push origin $BUMP_VERSION

