name: Build Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1

      - name: Build poetry
        run: |
          poetry install
          poetry version patch
          VERSION=$(poetry version --short)
          git add pyproject.toml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "bump up $VERSION version from workflow"
          git push

      - name: Create and Push Tag
        run: |
          VERSION=$(poetry version --short)
          GIT_TAG="v$VERSION"
          git tag $GIT_TAG
          git push origin $GIT_TAG
