name: Build and Publish Package & Push Git Tag

on:
  workflow_dispatch:
    inputs:
      bump_version:
        type: choice
        description: 'Bump version'
        required: true
        default: 'patch'
        options:
          - 'patch'
          - 'minor'
          - 'major'

jobs:
  build-publish-pkg-push-tag:
    name: Build and Publish Package & Push Git Tag
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Show envs
        run: env
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - uses: snok/install-poetry@v1

      - name: Build and Publish to PYPI
        env:
          POETRY_REQUESTS_TIMEOUT: 60
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          poetry version ${{ inputs.bump_version }}
          poetry build
          poetry publish --skip-existing

      - name: Push bump commit and Create Tag
        run: |
          BUMP_VERSION=v$(poetry version --short)
          git checkout -B github-release-$BUMP_VERSION
          git add pyproject.toml
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "bump up $BUMP_VERSION version from workflow"
          # git push -u origin github-release-$BUMP_VERSION
          # git tag $BUMP_VERSION
          # git push origin $BUMP_VERSION
          echo "RELEASE_BRANCH_NAME=github-release-$BUMP_VERSION" >> $GITHUB_ENV

      - name: Create pull request
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git status
          git diff
          gh pr create -B $RELEASE_BRANCH_NAME -H main --title 'Merge $RELEASE_BRANCH_NAME into main' --body 'Created by Github action'

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: snok/install-poetry@v1

      - name: Build docs
        run: |
          poetry install
          # cd docs
          # poetry run make html
          # touch ./build/html/.nojekyll
          echo "Foo build docs"

      # - name: Push docs to gh-pages
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: docs/build/html # The folder the action should deploy.

